services:
  api:
    build: .
    ports:
      - 5500:5000
    restart: always
  redis:
    image: 'redis:6.0-alpine'
    volumes:
      - /redis/data:/data
    ports:
      - 6379:6379
    restart: always
