services:
  api:
    restart: always
    build: .
    ports:
      - 5500:5000
  redis:
    restart: always
    image: "redis:alpine"
    volumes:
      - /redis/data:/data
    ports:
      - 6379:6379
