services:
  api:
    build: .
    ports:
      - 5500:5000
    restart: always
  redis:
    image: 'redis:alpine'
    restart: always
    command: sh -c "redis-server && redis-cli monitor"
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  cache:
    driver: local
